let resturant = [
    {
        name: "Kolachi",
        city: "Karachi",
        address: " Do Darya , phase-8",
        phoneNumber: "+111666111",
        webSite: "http://www.kababjees.com",
        menu: {
            fastfood: {
                ChickenBurger: '350rs',
                Broast: '400rs',
                chickenSandwich: '550rs',
                curlyFries: '150rs',
                chickenNuggets: '350rs',
                pizza: '899rs',
                pizzaFries: '500rs',
            },
            desiFood: {
                butterChicken: '500rs',
                roganJosh: '900rs',
                tandooriChicken: '800rs',
                malaiKofta: '999rs',
                masalaChicken: '650',
                matarPaneer: '560',
            },
            seaFood: {
                fish: '680rs',
                prawn: '1100rs',
                lobster: '990rs',
                crab: '950rs',
                shirmp: '1200rs',

            }

        }

    }

]

let managerdetails = {
    first:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        },
    secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        },
    secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        },
    secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        },
    secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        },
    secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        },
    secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        },
    secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        },
    secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        },
    secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        },
    secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        },
    secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        },
    secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }, secondmangerdetail:
        {
            name: "felio",
            Age: "56",
            Birthdate: "65-6-19",
            Gender: "male",
            Maritalstatus: "triple",
            Nationality: 'hind',
            address: "baheadr bad seyrick floor 19",
            cnicnumber: "1234567XXXXXX",
            dateofhire: "1-dec-2001",
            RelationshipInformation: "",
            JobHistory: "start 28 october - 3 -dec-19",
            Education: "CA",
            salaryDate: "2",
            terminatedate: "-",
            socialSecurity: "none",
            Employment: "Type – Permanen",
            EmploymentStatus: "Active",
            DateofJoining: '1st April 2014',
            NameofBank: "ACME Corp",
            BankAccountnumber: "XXXXXXXXXX2018",
            Workweek: "– Monday to Friday",
            Lastdayofworking: "– NA"
        }


},


